# Generated by Django 6.0.1 on 2026-02-02 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('size', models.PositiveIntegerField(help_text='Size in square feet')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('property_type', models.CharField(choices=[('home', 'Home'), ('apartment', 'Apartment')], db_index=True, default='home', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_added'],
            },
        ),
    ]
